### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by w3d0wn**
One Question tho: In which way is 
```
"date": "d.m.Y",
"time": "G:i"
```
relevant / what does it do? Or is it just displayed as option to check i. e.?

### CODE REVIEW

**Comment by Super-Baleine** [comment]
@dclement8 can you please reply to that?

**Comment by dclement8** [comment]
Hi, it's about date/time format to use for this language (dd.mm.yyyy here).
We use date function in PHP to display a date (http://php.net/manual/en/function.date.php) with the format defined in first argument.

**Comment by w3d0wn** [comment]
Alright, then can be merged

**Comment by Super-Baleine** [comment]
@dclement8 can you please merge de.json into muonium/core and deploy it straight away?

**Comment by Super-Baleine** [comment]
@w3d0wn thank you a lot for maintaining the German translations! We're very grateful!

**Pull request merged**
