### PR TITLE
Remove tabs

### PR DESCRIPTION
**Pull request by N3tt3rm4n**
I thought it'd be fun removing all those tabs... 🐳

### CODE REVIEW

**Comment by N3tt3rm4n** [comment]
Ups it seems I used an old version? I'll fix that

**Comment by Super-Baleine** [comment]
Hi 🐳 
Please, solve the conflicts. :)

**Comment by Super-Baleine** [comment]
> Ups it seems I used an old version? I'll fix that

Thanks! :)

**Comment by N3tt3rm4n** [comment]
Fixed... I'm so genius :P

**Comment by Super-Baleine** [comment]
haha, gg! 🐳

**Pull request merged**
