### PR TITLE
Create core spanish translation

### PR DESCRIPTION
**Pull request by victorhck**
spanish translation for core code.

### CODE REVIEW

**Comment by Super-Baleine** [comment]
Thanks a lot! I'm going to deploy your changes.

**Comment by victorhck** [comment]
A pleasure! :)
Maybe it's time to open an account to check how it works, and if everything it's translated ok... :)
've phun!

**Comment by Super-Baleine** [comment]
hey come on, you should've done that a while ago! haha

**Comment by victorhck** [comment]
BTW I can't understand the concept: "Password" and "secret password". Both are secrets, aren't they?
I know that one it's for login and other for encrypt the files, and even fot you it's a secret...

**Comment by Super-Baleine** [comment]
Actually, at first we called the "Secret Password" as "Passphrase", but people don't know what is a passphrase, so we've gone for Secret Password... People now know very well that's for the encryption.

Yes, both are secret. But not managed the same way. For instance, we don't send the Secret password. Your secret password is never sent to the servers. But your login password is (after being hashed, and is hashed again on the server).

**Comment by w3d0wn** [comment]
If the secret password isn't send to the servers, that means encryption/decryption happens client side, doesn't it? Can't that be used as a security breach? (I did not look at the code yet, but usually client side is JS and can be manipulated...)

Btw I feel password vs secret password can be confusing, how about 'login password' instead of 'password'?

And another btw: I think a redesign of the website for search engine optimization (and to be more responsive/adaptive) 'd be useful since when I googled 'Muonium' the first results were artictes about the Muonium atom which actually isn't that popular ;)

**Comment by Super-Baleine** [comment]
Yes. All the cryptography is client-side. That's why even we, the Muonium team, can't access your data. Because that's encrypted on your devices, hence we don't have any key. The thing is, if your device is compromised, then we can't help you. Muonium isn't magic ;)

Yes, I think login password would fit better. Although, up to now, we feel like the users understand very well the difference and the meaning of each.

Yes, we're currently working on a new design for the website.

**Pull request merged**
