### PR TITLE
Polish

### PR DESCRIPTION
**Pull request by ghost**
New translation.
For the website I have to finish (I send you email with questions about this).

### CODE REVIEW

**Comment by Super-Baleine** [comment]
Hey! Thanks for your work, that's really cool!

But, I see two pull requests, which one should I merge?

**Comment by ghost** [comment]
I think both, the first one it's about core, and the second one - I create new branch and start translation for the website. Sow I think you should merge both requests (I just starting with github ;) )

**Comment by Super-Baleine** [comment]
Ok, I'm going to merge only this one since the core translation is also there :)

**Comment by Super-Baleine** [comment]
Yes, I replied to your email :)

**Comment by Super-Baleine** [comment]
Can I update the application with your current translations for core? Or they're not completed yet? (for core only, I'm not talking about website)

**Comment by ghost** [comment]
Yes, you can. Even better, when you update app - then I can check what should be better for polish people.

**Comment by Super-Baleine** [comment]
Sure, hold on a few minutes, I'm updating it.

**Comment by Super-Baleine** [comment]
Seems there are errors in the json file. I'm looking at it. Please tell me if you find an error.

**Comment by ghost** [comment]
Yes, I found one.
It's comma in the 230 line

**Comment by dclement8** [comment]
I corrected, thanks :+1:

**Comment by ghost** [comment]
That was the error?

**Comment by Super-Baleine** [comment]
The error was the comma thing ;)

**Pull request merged**
