### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by Rapha0814**
I finished the job that I told you before (#49 )
As I commented in commit msg, in Korea we use 'password' and 'secret password' as the same meaning.
I think translating this would make users confused, so I left it in English.
Let me know if there's anything wrong.

### CODE REVIEW

**Comment by Super-Baleine** [comment]
Hey,

First of all, thank you a lot of all your work that you've done here :tada: :)

Regarding "secret password": how do you say passphrase in Korean?

**Comment by Rapha0814** [comment]
In Korea, some foreign languages just call it after its pronunciation. And
passphrase is one of them.

We call passphrase a "패스프레이즈" and Korean dictionary says "In general, a
password that has a longer string than the password used for digital
signature, encryption or decode ".

And we call password a "패스워드 or 비밀번호" and Korean dictionary says "A
password is a unique string of characters that you can pass to your
computer to identify legitimate users".

We often use "password", "secret password", "personal identification
number" mixed together.

2018-05-28 20:26 GMT+09:00 Paul Feuvraux <notifications@github.com>:

**Comment by Super-Baleine** [comment]
ok, so instead of secret password, maybe you can put "passphrase" (of course in Korean), what do you think?

**Comment by Rapha0814** [comment]
Oh, it will be better to use that.I'll reflect it and then make p.r
null

**Comment by Super-Baleine** [comment]
Indeed. Thank you a lot for your hard work :)

**Comment by Rapha0814** [comment]
It's my pleasure : )

**Pull request merged**
